version: "3.7"
services:
  sonar:
    image: sonarqube:8.7.1-community
    volumes:
      - ./tmp/data:/opt/sonarqube/data
      - ./tmp/logs:/opt/sonarqube/logs
      - ./tmp/extensions:/opt/sonarqube/extensions
    ports:
      - "9000:9000"
    environment: 
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=doutorequemtemdoutorado
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgresql/sonar
    depends_on: 
      - postgresql
  postgresql:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_DB=sonar
      - POSTGRES_PASSWORD=doutorequemtemdoutorado
    ports:
        - 5432:5432
    volumes:
        - .tmp/postgresql/data:/var/lib/postgresql/data